### ISSUE TITLE
Bootstrap3 (Requests for Template Support)

### ISSUE THREAD

**Issue by christian-wantia** [zioth/dokuwiki_fastwiki#26] opened 2016-12-04 07:25 UTC
There seem to be a problem with mode switching. Without reloading the page, for example, the site tools (index, media manger, etc.) are not working properly. It's reproducable with the following setup:

- DokuWiki Release 2016-06-26a "Elenor of Tsort"
- Bootstrap3 (Bootswatch Theme: Flatly)
- default settings

For the moment it helps using the media manager oder index via right click and new tab.

Update: As a workaround I've reduced m_supportedActions in script.js to edit, draft, show and save.

**Comment by zioth** [comment] 2016-12-05 02:21
I just installed bootstrap3, and I can't reproduce the bug. Is there a site you can point me to?

**Comment by zioth** [comment] 2017-11-06 00:00
Any update? If not, I'm going to close this ticket.

**Comment by zioth** [comment] 2017-11-12 23:29
@christian-wantia 

Closing. If you're able to tell me how to reproduce the bug, or can point me to a site where it's broken, I'll be happy to take a look.

**Closed by zioth** 2017-11-12 23:29 UTC
Labels: enhancement
