### ISSUE TITLE
Conflicts with struct plugin

### ISSUE THREAD

**Issue by micgro42** [zioth/dokuwiki_fastwiki#25] opened 2016-11-02 13:14 UTC
Hi,
unfortunately this plugin causes the struct autocompletion / datepicker to be missing on `do=edit`-views. I'm not sure if this has to be fixed here or within the struct-plugin.

**Comment by zioth** [comment] 2016-11-02 13:28
I don't think edit-views is a standard Doku action. I'm probably just searching for do=edit, and not taking extra characters in the action into account.

**Comment by zioth** [comment] 2017-01-16 16:17
My guess was wrong. Where are you seeing this do=edit-views mode?

**Comment by zioth** [comment] 2017-11-06 00:03
Any update @micgro42 ?

**Comment by micgro42** [comment] 2017-11-06 08:25
I will check. Thank you for reminding me, that this issue is still open 🙂

**Comment by zioth** [comment] 2017-11-06 15:06
@micgro42 I just installed the struct plugin and tried to quickly figure it out, but it's going to take longer. If you let me know how to reproduce the bug, I can take a look.

**Comment by micgro42** [comment] 2017-11-13 20:31
I can confirm that the issue still exists.

Basic steps to reproduce:
* install the struct plugin (and sqlite plugin as a dependency)
* go to the admin section, to "struct schema editor"
* create a new page schema by entering some schema name (e.g. `foobar`) and pressing save
* entering a name for the first field (e.g. `fastwikitestdate`)
* **select `Date` from the dropdown to the right**
* press the `Save` button in the lower left corner of the page
* Now in the table of contents choose `Struct Schema Assignments` (You could get there via the admin menu as well)
* assign the schema to every page by putting `**` (i.e. two asterisks) into the input field in the column `Page/Namespace`, select the schema we created and click the `Add`-Button
* Edit any page through fastwiki's section editor

**Comment by zioth** [comment] 2017-11-13 20:59
Thanks! I can now reproduce it.

The issue is that struct does some initialization when the page is loaded, but the fastwiki inline editor isn't initialized until after that. Unfortunately, this is difficult to fix because of the way struct is implemented. Each js file executes inside a jquery load closure. It also has to execute inside a fastwiki event, but the way it's written right now, every JS file would have to be loaded on the page twice, doubling the size of struct's JS. If the code were restructured slightly (for example, to use constructors instead of @includes), it would be easier to fix.

Here's the hacky, JS-doubling fix -- add this to the bottom of struct/script.js:

```javascript
jQuery(window).on('fastwiki:afterSwitch', function(evt, viewMode, isSectionEdit, prevViewMode) {
	jQuery(function () {
		/* DOKUWIKI:include script/functions.js */

		/* DOKUWIKI:include script/EntryEditor.js */
		EntryEditor(jQuery('#dw__editform, form.bureaucracy__plugin'));

		/* DOKUWIKI:include script/SchemaEditor.js */
		SchemaEditor();

		/* DOKUWIKI:include script/LookupEditor.js */
		jQuery('div.structlookup table').each(LookupEditor);

		/* DOKUWIKI:include script/InlineEditor.js */
		InlineEditor(jQuery('div.structaggregation table'));
            });
    });
```

**Comment by zioth** [comment] 2017-11-13 21:05
After some more testing, it's not so bad. Replace all of script.js with this:

```javascript
(function() {
    /* DOKUWIKI:include script/functions.js */
    /* DOKUWIKI:include script/EntryEditor.js */
    /* DOKUWIKI:include script/SchemaEditor.js */
    /* DOKUWIKI:include script/LookupEditor.js */
    /* DOKUWIKI:include script/InlineEditor.js */

    function init() {
        EntryEditor(jQuery('#dw__editform, form.bureaucracy__plugin'));
	SchemaEditor();
        jQuery('div.structlookup table').each(LookupEditor);
        InlineEditor(jQuery('div.structaggregation table'));
    }

    jQuery(init);

    jQuery(window).on('fastwiki:afterSwitch', function(evt, viewMode, isSectionEdit, prevViewMode) {
    	    if (isSectionEdit) {
    	    	init();
    	    }
    });
});
```

**Comment by zioth** [comment] 2017-11-13 21:12
I've submitted the fix in a struct ticket:

https://github.com/cosmocode/dokuwiki-plugin-struct/issues/351

**Comment by zioth** [comment] 2018-04-24 23:25
This fix was merged into the struct plugin on January 2, 2018.

**Closed** 2018-04-24 23:25 UTC
Labels: bug
